# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - first2apply-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      # Set up pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Cache pnpm dependencies
      - name: Resolve pnpm store path
        id: pnpm-store
        run: echo "store=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Init pnpm store dir
        run: mkdir -p "${{ steps.pnpm-store.outputs.store }}"

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.store }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install
        working-directory: apps/webapp

      # Build the webapp
      - name: Build the webapp
        run: pnpm run build
        working-directory: apps/webapp

      - name: Prepare deployment bundle
        run: |
          mkdir -p deploy
          cp -r apps/webapp/.next/* deploy/
          cp apps/webapp/package.json deploy/
          mkdir -p deploy/node_modules/next
          cp -r node_modules/next deploy/node_modules/next
          ls -R deploy

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: f2a-webapp
          path: deploy
          include-hidden-files: true
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: f2a-webapp
          path: deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65DC82FDFDD2450294C3F8944B65B24B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC4670B8769A4029B8729477F3133146 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB633ED21FFD4C4884DF3336EBB0DE20 }}

      - name: List build output
        run: ls -la apps/webapp/.next

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'first2apply-webapp'
          slot-name: 'Production'
          package: deploy
